spring:
  application:
    name: spring_ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5
          temperature: 0.8

logging:
  level:
    org.springframework.ai:
      chat.client: debug

